package fr.tikione.steam.cleaner.gui.dialog;

import fr.tikione.steam.cleaner.util.GraphicsUtils;
import fr.tikione.steam.cleaner.util.Log;
import fr.tikione.steam.cleaner.util.Translation;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.WindowConstants;

/**
 * Informations ("About") window.
 */
@SuppressWarnings("serial")
public class JDialogAbout extends JDialog {

    /** 
     * Create new form JDialogAbout.
     *
     * @param parent the parent component.
     * @param modal indicates if the frame is modal.
     * @param translation the program language translation handler.
     */

    public JDialogAbout(java.awt.Frame parent, boolean modal, Translation translation) {
        super(parent, modal);
        initComponents();
        initTranslateComponents(translation);
        GraphicsUtils.setFrameCentered(this);
        try {
            URL url = JDialogAbout.class.getResource("/fr/tikione/steam/cleaner/gui/tikione-steam-cleaner.png");
            Toolkit kit = Toolkit.getDefaultToolkit();
            Image img = kit.createImage(url);
            jLabelAbout.setIcon(new ImageIcon(img));
            setTitle(translation.getString(Translation.SEC_WABOUT, "frameTitle"));
            jTextAreaMessage.setText(
                    translation.getString(Translation.SEC_WABOUT, "author")
                    + "\r\n"
                    + translation.getString(Translation.SEC_WABOUT, "dev")
                    + "\r\n"
                    + translation.getString(Translation.SEC_WABOUT, "dep1"));
        } catch (Exception ex) {
            Log.error(ex);
        }
    }

    private void initTranslateComponents(Translation translation) {
        jButtonClose.setText(translation.getString(Translation.SEC_WABOUT, "button.close"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jTextAreaMessage = new JTextArea();
        jSeparator1 = new JSeparator();
        jButtonClose = new JButton();
        jLabelAbout = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new Color(255, 255, 255));

        jTextAreaMessage.setEditable(false);
        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setFont(new Font("Dialog", 0, 12)); // NOI18N
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setBorder(BorderFactory.createEmptyBorder());

        jButtonClose.setFont(new Font("Dialog", 1, 11)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.setFocusable(false);
        jButtonClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelAbout.setFont(new Font("Dialog", 0, 13)); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextAreaMessage, GroupLayout.PREFERRED_SIZE, 638, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
                            .addComponent(jButtonClose, Alignment.TRAILING)
                            .addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelAbout, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.UNRELATED)
                .addComponent(jTextAreaMessage, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(ComponentPlacement.RELATED)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButtonClose;
    private JLabel jLabelAbout;
    private JPanel jPanel1;
    private JSeparator jSeparator1;
    private JTextArea jTextAreaMessage;
    // End of variables declaration//GEN-END:variables
}
